# Generated by Django 4.2.2 on 2023-07-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "lastName",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Last Name"
                    ),
                ),
                ("age", models.IntegerField(null=True)),
                ("date", models.DateField(null=True)),
                (
                    "gmail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Gmail"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")], max_length=1
                    ),
                ),
                (
                    "profilePic",
                    models.ImageField(max_length=50, upload_to="Profile/Pictures/"),
                ),
                ("cv", models.FileField(max_length=50, upload_to="Profile/Files/")),
                (
                    "shortVideo",
                    models.FileField(max_length=50, upload_to="Profile/Video"),
                ),
                ("description", models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
