# Generated by Django 4.2.2 on 2023-07-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProfileApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="date",
            new_name="dateOfBirth",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="profilePic",
            new_name="profilePicture",
        ),
    ]
